name: export_docs
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  ansix:
    path: ../..
  image: ^4.5.4
  path: ^1.8.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
